image:
  file: .gitpod.Dockerfile # for playwright browser testing

ports:
  - port: 3000
    onOpen: ignore

tasks:
  - init: PLAYWRIGHT_BROWSERS_PATH=0 npm install
  - command: npm run dev
    name: Webpack dev server
